apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld
  namespace: doks-ci-cd
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/knative/helloworld-go:latest
          env:
            - name: TARGET
              value: "Go Sample v2"
  traffic:
  - percent: 50
    revisionName: helloworld-00001
  - percent: 50
    revisionName: helloworld-00002
