apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tag-header
  namespace: default
spec:
  template:
    metadata:
      name: tag-header-revision-1
    spec:
      containers:
      - image: ghcr.io/knative/helloworld-go:latest
        env:
        - name: TARGET
          value: "First Revision"
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tag-header
  namespace: default
spec:
  template:
    metadata:
      name: tag-header-revision-2
    spec:
      containers:
      - image: ghcr.io/knative/helloworld-go:latest
        env:
        - name: TARGET
          value: "Second Revision"
  traffic:
  - revisionName: tag-header-revision-1
    percent: 0
    tag: rev1
  - revisionName: tag-header-revision-2
    percent: 100
